[project]
name = "rajeshdas"
version = "0.1.1a1"
description = "A CLI persona app that showcases Rajesh Das's work, projects, and engineering mindset in the terminal"
readme = "README.md"
authors = [{ name = "Rajesh Das", email = "rajesh@hyperoot.dev" }]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
rajeshdas = "rajeshdas:main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
