[tools]
python = "3.13"
uv = "latest"
pre-commit = "latest"
git-cliff = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[hooks]
enter = "bash ./scripts/enter_project.sh"

[env]
UV_LINK_MODE = "copy"

[tasks.dev]
description = "Dev Mode"
run = 'uv run textual serve "python -m hyperoot.app"' # http://localhost:8000/
