[project]
name = "hyperoot"
version = "0.1.0"
description = "A Textual-based framework for building terminal portfolio applications"
readme = "README.md"
authors = [{ name = "Rajesh Das", email = "rajesh@hyperoot.dev" }]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
hyperoot = "hyperoot:main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
